/**
 * Tests for the NetMax trial-registry Worker logic.
 * Run with: node --test   (node >= 18; no dependencies, no D1 needed —
 * the D1 store is exercised through the in-memory shim in src/store.js,
 * which implements the identical adapter contract.)
 */
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import {
  validFingerprint,
  utcNowIso,
  addDaysIso,
  mintToken,
  tokensEqual,
  tokenOk,
  handleActivate,
  handleStatus,
  defaultConfig,
  TRIAL_DAYS,
  DENY_VM_TRIALS,
} from "../src/trial.js";
import { createMemoryStore } from "../src/store.js";

const SECRET = "test-secret-for-unit-tests-001";
const FP = "f".repeat(64);
const FP2 = "e".repeat(64);
const IP = "203.0.113.7";
// Fixed clock: 2026-10-09T15:27:30Z
const T0 = Date.UTC(2026, 9, 9, 15, 27, 30);

function cfg(overrides = {}) {
  return { ...defaultConfig(), activateLimit: 1000, statusLimit: 1000, ...overrides };
}

describe("fingerprint validation", () => {
  it("accepts 64 lowercase hex", () => assert.equal(validFingerprint("a".repeat(64)), true));
  it("rejects uppercase hex", () => assert.equal(validFingerprint("A".repeat(64)), false));
  it("rejects short input", () => assert.equal(validFingerprint("a".repeat(63)), false));
  it("rejects long input", () => assert.equal(validFingerprint("a".repeat(65)), false));
  it("rejects a raw hardware UUID (not the digest)", () =>
    assert.equal(validFingerprint("E4A2B1C3-0000-0000-0000-000000000000"), false));
  it("rejects non-strings", () => {
    assert.equal(validFingerprint(null), false);
    assert.equal(validFingerprint(undefined), false);
    assert.equal(validFingerprint(123), false);
  });
});

describe("timestamps", () => {
  it("formats as YYYY-MM-DDTHH:MM:SSZ with no fractional part", () => {
    assert.equal(utcNowIso(T0), "2026-10-09T15:27:30Z");
  });
  it("strips milliseconds like Python strftime does", () => {
    assert.equal(utcNowIso(T0 + 789), "2026-10-09T15:27:30Z");
  });
  it("adds TRIAL_DAYS exactly", () => {
    assert.equal(addDaysIso("2026-10-09T15:27:30Z", TRIAL_DAYS), "2026-10-23T15:27:30Z");
    assert.equal(TRIAL_DAYS, 14);
  });
});

describe("token scheme (byte-compatibility with trial_server/server.py)", () => {
  // Vector generated by the Python reference implementation:
  //   hmac.new(b"test-vector-secret-001",
  //            b"aaa...a|2026-10-09T15:27:30Z|2026-10-23T15:27:30Z",
  //            hashlib.sha256).hexdigest()
  const VEC = {
    secret: "test-vector-secret-001",
    fp: "a".repeat(64),
    start: "2026-10-09T15:27:30Z",
    end: "2026-10-23T15:27:30Z",
    token: "2dbb66b7ac20a1caeedddc30a42b055f033c0b7fd8c14202c0f8843dff5cb27c",
  };

  it("reproduces the Python server's token byte-for-byte", async () => {
    const got = await mintToken(VEC.secret, VEC.fp, VEC.start, VEC.end);
    assert.equal(got, VEC.token);
  });

  it("is deterministic", async () => {
    assert.equal(
      await mintToken(SECRET, FP, "2026-10-09T15:27:30Z", "2026-10-23T15:27:30Z"),
      await mintToken(SECRET, FP, "2026-10-09T15:27:30Z", "2026-10-23T15:27:30Z"),
    );
  });

  it("tokenOk accepts a genuine token", async () => {
    const t = await mintToken(SECRET, FP, "2026-10-09T15:27:30Z", "2026-10-23T15:27:30Z");
    assert.equal(await tokenOk(SECRET, FP, "2026-10-09T15:27:30Z", "2026-10-23T15:27:30Z", t), true);
  });

  it("rejects a tampered token (last nibble flipped)", async () => {
    const t = await mintToken(SECRET, FP, "2026-10-09T15:27:30Z", "2026-10-23T15:27:30Z");
    const bad = t.slice(0, -1) + (t.endsWith("0") ? "1" : "0");
    assert.equal(await tokenOk(SECRET, FP, "2026-10-09T15:27:30Z", "2026-10-23T15:27:30Z", bad), false);
  });

  it("rejects a token minted for a different window", async () => {
    const t = await mintToken(SECRET, FP, "2026-10-09T15:27:30Z", "2026-10-23T15:27:30Z");
    assert.equal(await tokenOk(SECRET, FP, "2026-10-09T15:27:30Z", "2026-10-24T15:27:30Z", t), false);
  });

  it("tokensEqual is constant-time safe on types and lengths", () => {
    assert.equal(tokensEqual("ab", "ab"), true);
    assert.equal(tokensEqual("ab", "ac"), false);
    assert.equal(tokensEqual("ab", "abc"), false);
    assert.equal(tokensEqual(null, "ab"), false);
    assert.equal(tokensEqual("ab", 12), false);
  });
});

describe("POST /v1/trial/activate", () => {
  it("activates a fresh fingerprint with a 14-day window and verifiable token", async () => {
    const store = createMemoryStore();
    const r = await handleActivate({
      store, secret: SECRET,
      body: { fingerprint_sha256: FP, app_version: "1.0.7", vm_suspected: false },
      ip: IP, nowMs: T0, config: cfg(),
    });
    assert.equal(r.status, 200);
    assert.equal(r.body.ok, true);
    assert.equal(r.body.trial_start, "2026-10-09T15:27:30Z");
    assert.equal(r.body.trial_end, "2026-10-23T15:27:30Z");
    assert.equal(await tokenOk(SECRET, FP, r.body.trial_start, r.body.trial_end, r.body.token), true);
  });

  it("rejects a duplicate activation and records the abuse signal", async () => {
    const store = createMemoryStore();
    const base = { store, secret: SECRET, ip: IP, nowMs: T0, config: cfg() };
    await handleActivate({ ...base, body: { fingerprint_sha256: FP, vm_suspected: false } });
    // NOTE: vm_suspected must be false here — like the Python server, the VM
    // check runs before the duplicate check, so a VM-flagged duplicate would
    // come back vm_not_allowed instead of trial_already_consumed.
    const dup = await handleActivate({ ...base, body: { fingerprint_sha256: FP, vm_suspected: false } });
    assert.equal(dup.status, 403);
    assert.equal(dup.body.error, "trial_already_consumed");
    assert.equal(dup.body.trial_start, "2026-10-09T15:27:30Z");
    assert.equal(dup.body.trial_end, "2026-10-23T15:27:30Z");
    assert.equal(store._trials.get(FP).activation_count, 2); // db_touch ran
  });

  it("handles a concurrent-activation race as consumed, not 500", async () => {
    const store = createMemoryStore();
    const base = { store, secret: SECRET, ip: IP, nowMs: T0, config: cfg() };
    const [a, b] = await Promise.all([
      handleActivate({ ...base, body: { fingerprint_sha256: FP2 } }),
      handleActivate({ ...base, body: { fingerprint_sha256: FP2 } }),
    ]);
    const statuses = [a.status, b.status].sort();
    assert.deepEqual(statuses, [200, 403]);
    const loser = a.status === 403 ? a : b;
    assert.equal(loser.body.error, "trial_already_consumed");
  });

  it("denies suspected VMs when DENY_VM_TRIALS is on", async () => {
    assert.equal(DENY_VM_TRIALS, true);
    const store = createMemoryStore();
    const r = await handleActivate({
      store, secret: SECRET,
      body: { fingerprint_sha256: FP, vm_suspected: true },
      ip: IP, nowMs: T0, config: cfg(),
    });
    assert.equal(r.status, 403);
    assert.equal(r.body.error, "vm_not_allowed");
    assert.equal(store._trials.has(FP), false); // nothing recorded
  });

  it("allows suspected VMs when the toggle is off", async () => {
    const store = createMemoryStore();
    const r = await handleActivate({
      store, secret: SECRET,
      body: { fingerprint_sha256: FP, vm_suspected: true },
      ip: IP, nowMs: T0, config: cfg({ denyVmTrials: false }),
    });
    assert.equal(r.status, 200);
  });

  it("rejects malformed fingerprints and malformed bodies", async () => {
    const store = createMemoryStore();
    const base = { store, secret: SECRET, ip: IP, nowMs: T0, config: cfg() };
    for (const bad of [null, "x", 42, [1], "not-json-shape"]) {
      const r = await handleActivate({ ...base, body: bad });
      assert.equal(r.status, 400);
      assert.equal(r.body.error, "malformed_request");
    }
    for (const badFp of ["ABC", "z".repeat(64), "a".repeat(63), null]) {
      const r = await handleActivate({ ...base, body: { fingerprint_sha256: badFp } });
      assert.equal(r.status, 400);
      assert.equal(r.body.error, "malformed_fingerprint");
    }
  });

  it("rate-limits activations per IP", async () => {
    const store = createMemoryStore();
    const c = cfg({ activateLimit: 2 });
    const mk = (fp) => handleActivate({
      store, secret: SECRET, body: { fingerprint_sha256: fp },
      ip: IP, nowMs: T0, config: c,
    });
    assert.equal((await mk("a".repeat(64))).status, 200);
    assert.equal((await mk("b".repeat(64))).status, 200);
    const r = await mk("c".repeat(64));
    assert.equal(r.status, 429);
    assert.equal(r.body.error, "rate_limited");
  });
});

describe("GET /v1/trial/status", () => {
  async function activated(nowMs = T0) {
    const store = createMemoryStore();
    const act = await handleActivate({
      store, secret: SECRET,
      body: { fingerprint_sha256: FP, vm_suspected: false },
      ip: IP, nowMs, config: cfg(),
    });
    return { store, token: act.body.token };
  }

  it("reports active:true inside the window", async () => {
    const { store, token } = await activated();
    const r = await handleStatus({
      store, secret: SECRET, fp: FP, token, ip: IP,
      nowMs: T0 + 7 * 86400 * 1000, config: cfg(),
    });
    assert.equal(r.status, 200);
    assert.deepEqual(r.body, {
      ok: true, active: true,
      trial_start: "2026-10-09T15:27:30Z", trial_end: "2026-10-23T15:27:30Z",
    });
  });

  it("reports active:false after expiry", async () => {
    const { store, token } = await activated();
    const r = await handleStatus({
      store, secret: SECRET, fp: FP, token, ip: IP,
      nowMs: T0 + 15 * 86400 * 1000, config: cfg(),
    });
    assert.equal(r.status, 200);
    assert.equal(r.body.active, false);
  });

  it("rejects tampered tokens", async () => {
    const { store, token } = await activated();
    const bad = token.slice(0, -1) + (token.endsWith("0") ? "1" : "0");
    const r = await handleStatus({ store, secret: SECRET, fp: FP, token: bad, ip: IP, config: cfg() });
    assert.equal(r.status, 403);
    assert.equal(r.body.error, "bad_token");
  });

  it("404s unknown fingerprints", async () => {
    const { store } = await activated();
    const r = await handleStatus({
      store, secret: SECRET, fp: FP2, token: "0".repeat(64), ip: IP, config: cfg(),
    });
    assert.equal(r.status, 404);
    assert.equal(r.body.error, "unknown_fingerprint");
  });

  it("400s malformed fingerprints", async () => {
    const { store } = await activated();
    const r = await handleStatus({
      store, secret: SECRET, fp: "nope", token: "0".repeat(64), ip: IP, config: cfg(),
    });
    assert.equal(r.status, 400);
    assert.equal(r.body.error, "malformed_fingerprint");
  });

  it("rate-limits status checks per IP", async () => {
    const { store, token } = await activated();
    const c = cfg({ statusLimit: 1 });
    const base = { store, secret: SECRET, fp: FP, token, ip: IP, config: c };
    assert.equal((await handleStatus({ ...base, nowMs: T0 })).status, 200);
    const r = await handleStatus({ ...base, nowMs: T0 + 1000 });
    assert.equal(r.status, 429);
    assert.equal(r.body.error, "rate_limited");
  });
});
